- backend/.gitignore
- backend/src/main/java/com/caffe/global/aspect/ResponseAspect.java
- backend/src/main/java/com/caffe/global/rsData/RsData.java
src
└── main
└── java
└── com
└── caffe
│
├── 📁 global                // 💡 전역 공통 기능 패키지
│   │
│   ├── 📁 aspect
│   │   └── 📄 ResponseAspect.java  // 응답 형식을 자동 처리하는 Aspect
│   │
│   └── 📁 rsData
│       └── 📄 RsData.java          // 표준 응답 객체
> Be8 dooood

- .idea/gradle.xml
- .idea/vcs.xml
- backend/src/main/java/com/caffe/domain/shipping/entity/Shipping.java
- backend/src/main/java/com/caffe/shipping/ShippingController.java
- backend/src/main/java/com/caffe/shipping/ShippingRepository.java
- backend/src/main/java/com/caffe/shipping/ShippingService.java
- backend/src/main/resources/templates/sample.html
- sample.html에 다음(카카오) 주소 검색 API 연동
- 배송지, 우편번호 입력 기능 추가 및 스타일 일부 수정
- Controller, Service, Repository 틀만 잡기
> 다음 주소 API 연동, 틀 잡기

- backend/src/main/java/com/caffe/domain/purchase/entity/Purchase.java
- backend/src/main/java/com/caffe/domain/purchase/entity/PurchaseItem.java
- 패키지명 order → purchase로 변경
- entity 패키지 통합
- 양방향 연관 관계 설정
> 패키지명 order → purchase로 변경

- backend/src/main/java/com/caffe/domain/payment/entity/Payment.java
> fix: 패키지명 변경 반영

- backend/src/main/java/com/caffe/domain/shipping/entity/Shipping.java
> 추가 fix : package : shipping.entity.shipping

- backend/src/main/java/com/caffe/domain/purchase/entity/Purchase.java
user_email -> userEmail 변경했습니다.
> user_email -> userEmail 변경

- backend/src/main/java/com/caffe/global/jpa/entity/BaseEntity.java
- backend/src/main/java/com/caffe/global/security/SecurityConfig.java
> baseEntity 추가

- backend/src/main/java/com/caffe/domain/payment/controller/PaymentController.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentDto.java
- backend/src/main/java/com/caffe/domain/payment/repository/PaymentRepository.java
- backend/src/main/java/com/caffe/domain/payment/service/PaymentService.java
> payment 기본  구성

- backend/build.gradle.kts
- backend/src/main/java/com/caffe/HomeController.java
- backend/src/main/resources/static/css/style.css
- backend/src/main/resources/templates/fragments/footer.html
- backend/src/main/resources/templates/fragments/header.html
- backend/src/main/resources/templates/home.html
- backend/src/main/resources/templates/layout.html
> layout, header, footer 수정

- backend/build.gradle.kts
- backend/src/main/java/com/caffe/domain/product/entity/Product.java
- backend/src/main/java/com/caffe/domain/product/service/ProductService.java
- backend/src/main/resources/templates/product/detail_product.html
- backend/src/main/resources/templates/product/list_product.html
###예외처리 개선
에러 발생 시 적절한 HTTP 상태 코드 반환
사용자에게 명확한 에러 메시지 제공
유효성 검사 오류 처리 개선
###권한별 UI 제어
ADMIN 권한자만 상품 추가/수정/삭제 버튼 볼 수 있음
일반 사용자는 상품 조회만 가능
> Be8 beekeeper24

- backend/src/main/java/com/caffe/domain/product/controller/ProductApiController.java
- backend/src/main/java/com/caffe/domain/product/controller/ProductWebController.java
> api 주소 오류 수정 #3

- backend/src/main/java/com/caffe/domain/shipping/service/ShippingService.java
ShippingService
import com.caffe.domain.shipping.dto.ReceiverDto; 삭제했습니다.
> import com.caffe.domain.shipping.dto.ReceiverDto; 삭제

- backend/src/main/java/com/caffe/domain/purchase/dto/req/ReceiverReqDto.java
- backend/src/main/java/com/caffe/domain/shipping/controller/ShippingController.java
- backend/src/main/java/com/caffe/domain/shipping/dto/ShippingDto.java
- backend/src/main/java/com/caffe/domain/shipping/entity/Shipping.java
- backend/src/main/java/com/caffe/domain/shipping/entity/ShippingResDto.java
- backend/src/main/java/com/caffe/domain/shipping/service/ShippingService.java
- backend/src/main/resources/templates/sample.html
👩‍💻 요구 사항과 구현 내용
- 일단은 구매 연결 없이 배송 저장하도록 ShippingService 및 Controller 수정
- ReceiverReqDto에 우편번호, 이메일, 상태 필드 추가
- 연락처 010-xxxx-xxxx 형식 정규식 검증 추가
- 주소, 우편번호, 이메일, 이름, 연락처 필수 입력값 검증 로직 추가
- ShippingResDto 생성 및 저장 후 응답하도록 개선
- 불필요한 최신 구매 조회 API 제거
> 배송 저장 로직 리팩토링 및 입력값 검증 강화

- backend/src/main/java/com/caffe/domain/purchase/entity/Purchase.java
- backend/src/main/java/com/caffe/domain/purchase/entity/PurchaseItem.java
- backend/src/main/java/com/caffe/domain/purchase/entity/PurchaseStatus.java
- backend/src/main/java/com/caffe/domain/purchase/service/PurchaseService.java
- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- frontend/src/app/purchase/page.tsx
> 주문, 주문 제품 setter -> 생성자 변경

- backend/src/main/java/com/caffe/domain/purchase/dto/req/ReceiverReqDto.java
- backend/src/main/java/com/caffe/domain/purchase/service/PurchaseService.java
- backend/src/main/java/com/caffe/domain/shipping/controller/ShippingController.java
- backend/src/main/java/com/caffe/domain/shipping/entity/ShippingStatus.java
- backend/src/main/java/com/caffe/domain/shipping/service/ShippingService.java
- 배송 임시 저장 상태 추가
- ReceiverReqDto 에서 status 제외
> 배송 임시 저장 상태 추가

- backend/src/main/java/com/caffe/domain/payment/controller/ApiV1PaymentController.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentDto.java
- backend/src/main/java/com/caffe/domain/payment/entity/Payment.java
- backend/src/main/java/com/caffe/domain/payment/service/PaymentService.java
- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- backend/src/test/java/com/caffe/domain/payment/controller/ApiV1PaymentControllerTest.java
> payment 생성 & 요청 분리

- backend/src/main/java/com/caffe/domain/product/controller/ProductApiController.java
- backend/src/main/java/com/caffe/domain/product/controller/ProductWebController.java
- backend/src/main/java/com/caffe/domain/product/dto/ProductDTO.java
> ãrecord 사용

- backend/src/main/java/com/caffe/domain/product/controller/ProductApiController.java
- backend/src/main/java/com/caffe/domain/product/controller/ProductWebController.java
- backend/src/main/java/com/caffe/domain/product/dto/request/ProductCreateRequest.java
- backend/src/main/java/com/caffe/domain/product/dto/request/ProductSearchRequest.java
- backend/src/main/java/com/caffe/domain/product/dto/request/ProductUpdateRequest.java
- backend/src/main/java/com/caffe/domain/product/dto/response/ProductDetailResponse.java
- backend/src/main/java/com/caffe/domain/product/dto/response/ProductListResponse.java
- backend/src/main/java/com/caffe/domain/product/dto/response/ProductSummaryResponse.java
- backend/src/main/java/com/caffe/domain/product/repository/ProductRepository.java
> dto 응답,요청 분리

- backend/src/main/java/com/caffe/domain/product/controller/ProductApiController.java
- backend/src/main/java/com/caffe/domain/product/controller/ProductWebController.java
- backend/src/main/java/com/caffe/domain/product/repository/ProductRepository.java
- backend/src/main/java/com/caffe/domain/product/service/ProductService.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/templates/product/list_product.html
> 페이징 기능 추가, 페이지 크UI, 페이지 기본 사이즈 설정

- backend/src/main/java/com/caffe/domain/payment/constant/PaymentOptionType.java
- backend/src/main/java/com/caffe/domain/payment/constant/PaymentStatus.java
- backend/src/main/java/com/caffe/domain/payment/controller/ApiV1PaymentController.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentOptionDto.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentResponseDto.java
- backend/src/main/java/com/caffe/domain/payment/entity/Payment.java
- backend/src/main/java/com/caffe/domain/payment/entity/PaymentOption.java
- backend/src/main/java/com/caffe/domain/payment/repository/PaymentOptionRepository.java
- backend/src/main/java/com/caffe/domain/payment/service/PaymentService.java
- backend/src/main/java/com/caffe/global/globalExceptionHandler/GlobalExceptionHandler.java
- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- backend/src/test/java/com/caffe/domain/payment/controller/ApiV1PaymentControllerTest.java
> exception 추가

- frontend/src/app/components/Header.tsx
> 카테고리 url 수정

- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- 배송 초기데이터 추가
- 결제 전 임시 주문, 배송 데이터 추가
> feat: 배송 초기데이터, 결제전 데이터 추가

- backend/src/main/java/com/caffe/domain/purchase/constant/PurchaseStatus.java
- backend/src/main/java/com/caffe/domain/purchase/controller/PurchaseController.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchaseCheckoutResBody.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchaseDto.java
- backend/src/main/java/com/caffe/domain/purchase/entity/Purchase.java
- backend/src/main/java/com/caffe/domain/purchase/service/PurchaseService.java
- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- frontend/src/app/purchase/page.tsx
- frontend/src/app/purchase/types/purchase-response.ts
주문 결제 연결
- 주문 생성 후 주문 정보 응답
- 받은 정보로 결제 생성 api 호출
- 결제 코드 응답을 결제페이지로 전달
주문 페이지 수정
- 페이지 파라미터 받는 부분 동적 라우팅 -> 쿼리 파라미터로 변경
- 기본 결제 옵션 배열 체크
기타
- enum 패키지 별도 분리
> 주문 생성 후 결제 생성 및 결제 페이지 이동

- backend/src/main/java/com/caffe/domain/payment/controller/ApiV1PaymentController.java
- frontend/src/app/payment/page.tsx
> fix,test : 로그, 테스트 코드 삭제

- backend/src/main/java/com/caffe/CaffeApplication.java
- backend/src/main/java/com/caffe/domain/shipping/ShippingScheduler.java
- backend/src/main/java/com/caffe/domain/shipping/controller/ShippingController.java
- backend/src/main/java/com/caffe/domain/shipping/dto/ShippingDto.java
- backend/src/main/java/com/caffe/domain/shipping/dto/ShippingResDto.java
- backend/src/main/java/com/caffe/domain/shipping/entity/Shipping.java
- backend/src/main/java/com/caffe/domain/shipping/service/ShippingService.java
- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- frontend/src/app/shipping/list/page.tsx
- 오전 9시 스케줄러로 주문시간대별 배송 상태를 자동 업데이트 (BEFORE_DELIVERY → DELIVERING)
- React UI에서 10초마다 데이터 새로고침, 상태 변경 시 '배송중' 목록으로 자동 이동
- 테스트 환경에선 현재시간 기준 1분 후 스케줄러 실행하도록 설정(실제는 오전 9시)
- 안내문에 시간대별 로직, 새로고침, 자동 이동 기능 설명 추가
> 배송 스케줄링 & 실시간 UI 반영 기능 구현

- backend/src/main/java/com/caffe/domain/cart/controller/CartController.java
- backend/src/main/java/com/caffe/domain/cart/entity/Cart.java
- backend/src/main/java/com/caffe/domain/cart/repository/CartRepository.java
- backend/src/main/java/com/caffe/domain/cart/service/CartService.java
- backend/src/main/java/com/caffe/domain/purchase/controller/PurchaseController.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchaseAdmDto.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchaseDetailDto2.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchaseItemDto.java
- backend/src/main/java/com/caffe/domain/purchase/entity/Purchase.java
- backend/src/main/java/com/caffe/domain/purchase/repository/PurchaseRepository.java
- backend/src/main/java/com/caffe/domain/purchase/service/PurchaseService.java
- backend/src/main/java/com/caffe/global/initdata/BaseInitData.java
- backend/src/test/java/com/caffe/domain/payment/controller/ApiV1PaymentControllerTest.java
- frontend/src/app/purchase/lookup/detail/page.tsx
- frontend/src/app/purchase/types/purchase-response.ts
주문
- 관리자 주문 목록 조회 기능 추가
- 주문 - 주문제품 목록 조회 기능 추가
장바구니 (논의 필요)
- 장바구니 틀만 추가
> 관리자 주문 목록, 주문제품 목록 조회

- frontend/src/app/purchase/lookup/detail/page.tsx
- frontend/src/app/purchase/page.tsx
> 컴포넌트 위치 조정

- frontend/src/app/payment/execute/page.tsx
> rename : id/execute/page -> excute/page로 변경

- backend/src/main/java/com/caffe/domain/product/entity/Product.java
- backend/src/main/java/com/caffe/domain/purchase/service/PurchaseService.java
- frontend/src/app/purchase/page.tsx
- 주문 생성 전 재고 체크 
- 주문한 제품 장바구니(로컬 스토리지) 목록에서 제거
> 주문한 제품 장바구니에서 제거, 주문 생성 전 재고 체크 

- backend/src/main/java/com/caffe/domain/cart/controller/CartController.java
- frontend/src/app/products/[id]/page.tsx
> 상품 상세페이지 수량기능 추가

- backend/src/main/java/com/caffe/domain/product/entity/Product.java
- backend/src/main/java/com/caffe/domain/purchase/constant/PurchaseStatus.java
- backend/src/main/java/com/caffe/domain/purchase/controller/PurchaseController.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchaseAdmDto.java
- backend/src/main/java/com/caffe/domain/purchase/entity/Purchase.java
- backend/src/main/java/com/caffe/domain/purchase/service/PurchaseService.java
- frontend/src/app/components/Header.tsx
- frontend/src/app/purchase/list/page.tsx
- frontend/src/app/purchase/types/purchase-response.ts
- 주문 상태 변경 시 재고 수량 변경 
- 결제 서비스에 연결 필요
> 관리자 주문 목록 페이지 추가,  주문 상태 변경 시 재고 조정

- frontend/src/app/cart/page.tsx
문제 
- 개발 환경에서 H2 메모리/파일 DB를 초기화할 때 이런 문제가 자주 발생
- 서버의 DB 상태와 클라이언트의 localStorage에 저장된 장바구니 데이터의 불일치
- 이전에 장바구니에 담았지만, db에서는 삭제된 제품의 경우
- 로컬 스토리지에 남아있음
- productId로 요청 되며 404 Not Found 오류가 발생
해결
- localStorage의 장바구니 데이터와 서버의 제품 데이터를 동기화하고 유효하지 않은 데이터를 자동으로 정리
- 유효성 검사 및 flatMap을 이용한 데이터 필터링
> 로컬 스토리지 장바구니 데이터 불일치 해결

- frontend/src/app/products/[id]/page.tsx
- frontend/src/app/products/list/page.tsx
> fix:상품 상세페이지 관리자 버튼 삭제, 상품 목록페이지 관리자버튼 색 수정

- backend/src/main/java/com/caffe/domain/member/controller/MemberApiController.java
- backend/src/main/java/com/caffe/domain/product/controller/ProductApiController.java
- backend/src/main/java/com/caffe/domain/product/dto/request/ProductCreateRequest.java
- backend/src/main/java/com/caffe/domain/product/dto/request/ProductStatusUpdateRequest.java
- backend/src/main/java/com/caffe/domain/product/dto/request/ProductStockUpdateRequest.java
- backend/src/main/java/com/caffe/domain/product/entity/Product.java
- backend/src/main/java/com/caffe/domain/product/service/ProductService.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-test.yml
> fix: push 오류 해결

- backend/src/main/java/com/caffe/domain/payment/controller/ApiV1PaymentController.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentDetailOptionDto.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentOptionDto.java
- backend/src/main/java/com/caffe/domain/payment/dto/PaymentOptionsDto.java
- backend/src/main/java/com/caffe/domain/payment/repository/PaymentOptionRepository.java
- backend/src/main/java/com/caffe/domain/payment/service/PaymentService.java
- backend/src/main/java/com/caffe/domain/purchase/controller/PurchaseController.java
- backend/src/main/java/com/caffe/domain/purchase/dto/res/PurchasePageResBody.java
- backend/src/test/java/com/caffe/domain/payment/controller/ApiV1PaymentControllerTest.java
- frontend/src/app/payment/[id]/execute/page.tsx
- frontend/src/app/payment/[id]/page.tsx
- frontend/src/app/payment/components/bankForm/bankForm.tsx
- frontend/src/app/payment/components/options/optionsForm.tsx
- frontend/src/app/payment/page.tsx
- frontend/src/app/payment/types/paymentData.ts
###결제 단에서 결제 수단 변경 추가
###결제 옵션 전체 가져오는 api 추가
> feat : 결제 수단 변경 추가

- frontend/src/app/purchase/lookup/detail/page.tsx
- frontend/src/app/purchase/lookup/page.tsx
- frontend/src/app/purchase/page.tsx
> 알림 메시지 내용 rsdata 메시지 적용

- backend/src/main/java/com/caffe/domain/shipping/controller/ShippingController.java
- backend/src/main/java/com/caffe/domain/shipping/repository/ShippingRepository.java
- backend/src/main/java/com/caffe/domain/shipping/service/ShippingService.java
> 배송 단건 조회 추가

- frontend/src/app/components/Header.tsx
- frontend/src/app/page.tsx
- 로그인 x -> localhost:3000
- 로그인 o -> localhost:3000/products/list
- Caffe 메뉴 서비스 입니다. -> Team | 12로 변경해두었습니다. 더 적절한 문구가 있으시면 언제든 말씀해 주세요! 우선 급하게 작성했습니다.
> Be8 dlawhd

- backend/src/main/java/com/caffe/CaffeApplication.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/application.yml
> feat: backend실행 시 팀표시되게 추가, fix : DB 로그 수준 수정

- frontend/src/app/payment/[id]/execute/page.tsx
- frontend/src/app/payment/[id]/page.tsx
- frontend/src/app/payment/components/options/optionsForm.tsx
> fix : frontend/payment 오류 메세지/예외 처리  setError로 공통 변경

- frontend/src/app/purchase/page.tsx
- 다음 주소 검색 API 연동
- 주소 검색 버튼 추가
> 구매 페이지 주소 검색 기능 추가
